version: '3.8'

services:
  ledger-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: pocket-ledger-dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8080
      - JAVA_OPTS=-Xmx512m -Xms256m
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    networks:
      - ledger-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  ledger-network:
    driver: bridge

volumes:
  ledger-logs:
    driver: local